### ISSUE TITLE
[Bug] WebAuthenticator is not working properly on iOS 12

### ISSUE THREAD

**Issue by MookieFumi** [xamarin/Essentials#1482]
### Description

On iOS12 **doesn't appear the Issuer name** when the WebAuthenticator.AuthenticateAsync is called and the behavior is a little bit strange because **once the user is logged in the alert to login appears again**.

![Simulator Screen Shot - iPhone Xs - 2020-10-28 at 12 44 37](https://user-images.githubusercontent.com/4056557/97434748-c2ee2680-191f-11eb-8cd3-593debe3b9a2.png)

I have been implementing the WebAuthenticator on iOS 14 and it works properly as you can see in the image.

![Simulator Screen Shot - iPhone 11 - 2020-10-28 at 12 43 28](https://user-images.githubusercontent.com/4056557/97434703-b36edd80-191f-11eb-9399-92497a5e309d.png)

### Steps to Reproduce

1. Install Xamarin Essentials 1.5.3.2
2. Try to use the WebAuthenticator on iOS 12.4

### Expected Behavior

The issuer should appear in the alert instead of null and the strange behavior should be the same than on iOS 14.

### Actual Behavior

Described at the top of the issue.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: Visual Studio for MacOS
- Platform Target Frameworks: 
  - iOS:  12.4
- Nuget Packages:
  * Xamarin Essentials 1.5.3.2
  * Xamarin.Forms 4.8.0.1560
- Affected Devices:

**Comment by mattleibow** [comment]
This is an OS popup and not something that Essentials actually controls.

However, there has been several changes and fixes to the `WebAuthenticator` API, so check out `1.6.0-pre3` and that should fix it.

**Comment by mattleibow** [comment]
Closing this as I think the fixes in 1.6 should resolve this. Feel free to reopen if this is not the case.

**Comment by MNADEEMCH** [comment]
@mattleibow It's still happening on iOS 12(iPhone 6) When I open the specified url with redirect uri scheme after login with my apple/google account, not returning me back to my app. Please help
