### ISSUE TITLE
Location request failing to return or throw after permissions request when called from F# code.

### ISSUE THREAD

**Issue by RyanBuzzInteractive** [xamarin/Essentials#288]
EDIT : Example a couple of posts down

### Description

When I try to get location on iOS from my F# core library, I find that exceptions, such as caused by refusing permission, fail to throw.

If I call the same code from C#, it behaves as expected. I even tried making the call to the plugin in a C# method, and calling _that_ method from F#, but I found the same result.

I also find that F# does not continue the location request after granting permission, wheras C# does. In both cases, exceptions and permissions, the async location request never returns.

### Steps to Reproduce

EDIT : Use the sample posted below

### Expected Behavior

A PermissionException should be thrown

### Actual Behavior

Nothing happens, the task never returns

### Basic Information

- Version with issue: 0.6.0
- Last known good version: None
- IDE: Visual Studio 2017
- Platform Target Frameworks: 9.3 and up
  - iOS:  11.4

**Comment by niels9001** [comment]
Is this related to the following:

On Android, I'm trying to call:

`   GeolocationRequest request = new GeolocationRequest(GeolocationAccuracy.Low);
     var location = await Geolocation.GetLocationAsync(request);`

At GetLocationAsync I get the following error:

> Error while resolving expression: Object reference not set to an instance of an object

> {Java.Lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticVoidMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00069] in <7802aa64ad574c33adca332a3fa9706a>:0 
  at Java.Interop.JniPeerMembers+JniStaticMethods.InvokeVoidMethod (System.String encodedMember, Java.Interop.JniArgumentValue* parameters) [0x00018] in <7802aa64ad574c33adca332a3fa9706a>:0 
  at Android.Support.V4.App.ActivityCompat.RequestPermissions (Android.App.Activity activity, System.String[] permissions, System.Int32 requestCode) [0x00061] in <48bd37de3fc24aa3a0df3b93903114c1>:0 
  at Xamarin.Essentials.Permissions+<PlatformRequestAsync>d__9.MoveNext () [0x001a6] in <b16d1f73ae5a47eaab5f52d25a0ab01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Xamarin.Essentials.Permissions+<RequireAsync>d__3.MoveNext () [0x00060] in <b16d1f73ae5a47eaab5f52d25a0ab01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Xamarin.Essentials.Geolocation+<PlatformLocationAsync>d__6.MoveNext () [0x0007b] in <b16d1f73ae5a47eaab5f52d25a0ab01c>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at TestApp.Mobile.Views.MainPage+<GetLocation>d__5.MoveNext () [0x00041] in ***Page.cs:73 
  --- End of managed Java.Lang.NullPointerException stack trace ---
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.requestPermissions(java.lang.String[], int)' on a null object reference
	at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:479)
	at md5440e03ce5b057b6078b9acd731a190f3.MainActivity.n_onCreate(Native Method)
	at md5440e03ce5b057b6078b9acd731a190f3.MainActivity.onCreate(MainActivity.java:29)
	at android.app.Activity.performCreate(Activity.java:7026)
	at android.app.Activity.performCreate(Activity.java:7017)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1215)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6501)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
}

Looks like this happened after I have updated all the Xamarin.Android NuGet packages to the latest versions?

**Comment by RyanBuzzInteractive** [comment]
Hi there, no, I am on iOS and my problem is related to F# interop. I am trying  to make a repo app at the moment to demonstrate it.

**Comment by RyanBuzzInteractive** [comment]
Closed as my simple repro example seemed to work, so it must be something else in my main application.

**Comment by RyanBuzzInteractive** [comment]
Ok I have managed to reproduce it. Just deny permissions when asked, then alternate between calling the location service from C# and F# by commenting / uncommenting the appropriate line. C# will throw a permission exception, f# will never return.
[Example.zip](https://github.com/xamarin/Essentials/files/2099692/Example.zip)

**Comment by RyanBuzzInteractive** [comment]
I realise this might be an issue with the way F# async and C# Tasks interact, but it seems like it should work to the layman at least, and if I make a simple task which just throws an exception, then it will be thrown from either platform so again I think this should work.

**Comment by jamesmontemagno** [comment]
So I wasn't able to reproduce this in C# at all as it worked fine. Let me try an F# project.

**Comment by jamesmontemagno** [comment]
Maybe you can supply me a small repro as I don't know F# very well at all.

**Comment by RyanBuzzInteractive** [comment]
Hi James,
Thanks for looking at this for me. I'm not totally sure we are on the same page here, as you initially said couldn't "reproduce this in C#", but the problem is specifically with F#. Also the problem isn't getting location to work, it's catching exceptions when it doesn't.

 It also can't be a simulator problem as I observe different behaviour between the two languages when running on the same simulator.

Can you tell me - if you run my sample as a fresh installation, with the C# library call from the view controller active, and the F# lib call commented out, then deny location permission, do you see a location exception raised in the location service? I  have caught it and printed to the console fyi, so it won't crash.

Then, comment out the c# call and uncomment the call to the F# lib, then again run a fresh installation and deny permission. This time the exception is not raised.

Do you see anything different? Can you get any exception to propagate on F#?

**Comment by jamesmontemagno** [comment]
So, yes I do see this issue in your sample application that the exception does not get thrown for you some reason in that C# code... 

However in our sample application and test app with just C# it works just fine...

I'm not really an F# person, but I have to imagine it is not with our library at all. If it works from C# then should from F#... I will inquire more though.

**Comment by RyanBuzzInteractive** [comment]
Hi James,

I assume you meant "the exception does not get thrown for you some reason in that F# code...".

Again, thanks for digging at it for me. In my production code I wasn't even calling your plugin via c#, I was calling it directly from F#, so even simpler than the example. Basically this means that your plugin can't be used from F# which is a shame, and I guess this might affect others too perhaps?

For example, just start a plain F# project, no C# code at all, and call your plugin and deny permission, you will find the same.

I'm just starting to do my core work in F#, with my VMs and Xamarin code in C#, so I am probably in a fairly untested situation here.

I'm going to start work now and listen to Merge Conflict, cheers!

**Comment by RyanBuzzInteractive** [comment]
Can we also open this as a bug again, as it wasn't solved? Thanks.

**Comment by jamesmontemagno** [comment]
It is open :) 

I will say that I was able to get results back just fine when the user accepted the permissions here so the library itself would work just fine. My assumption here is that something in the F# call is block or swallowing the exception as the app is still responsive. 

My thinking is the F# code is wonky perhaps or something is happening there. I am going to look further here.

**Comment by RyanBuzzInteractive** [comment]
Hey James,

Sorry I meant add the bug tag, or at least remove the 'invalid, unable to reproduce' as it does exist and you could reproduce it with my sample, and others may pick it up if they see it - I was just worried it might be ignored otherwise.

I did think it might be the way the task completions are being handled between the C# Task and F# Async systems, it feels like the likely cause. Basic exceptions work fine between the systems, but I think maybe there is something in the location plugin which has exposed a more complex error case.

I would say that being able to catch the location denied permission is a vital part of the plugin.

Also it isn't limited to the exceptions, for example the initial location is never returned if you do accept the permission. You have to stop and start updates again to get it. Again, it's the continuation after the request that is the problem.

It definitely *isn't* my simulator location, which is set and also location updates work fine after stopping / starting them post-acceptance. 

Thanks again for digging,
Ryan

**Comment by RyanBuzzInteractive** [comment]
Thanks :) Do you reckon it might be worth me posting this on the F# repo issues, and linking them? Since it may well be that end of things.

**Comment by jamesmontemagno** [comment]
I have asked our F# team to take a look here.

**Comment by RyanBuzzInteractive** [comment]
Awesome, you're a legend :)

**Comment by dsyme** [comment]
@RyanBuzzInteractive I'm not certain but it is possible you need this or some variation of this: http://www.fssnip.net/7Rc/title/AsyncAwaitTaskCorrect

However I think that's to avoid seeing AggregateException (and see the specific exception instead), so I'm not certain it deals with "Nothing happens, the task never returns"

I'll be able to help with this tomorrow, unfortunately I need to go out now.

**Comment by RyanBuzzInteractive** [comment]
Hey @dsyme , thanks for that. I actually found that exact post and tried it but it didn't seem to make a difference.

**Comment by dsyme** [comment]
@RyanBuzzInteractive You might want `Async.StartAsTaskImmediate`.  That starts on the current thread (likely the UI thread) rather than in the thread pool

**Comment by RyanBuzzInteractive** [comment]
I should also reiterate that the title of this bug relates to exceptions which aren't thrown, but as I explained above I also never see the task return with location even if I do grant permission. If I request a second time (permissions are already granted) then it works no problem.

**Comment by RyanBuzzInteractive** [comment]
Updated the title to try to be more accurate. Feel free to reword it though, still feels clunky...

**Comment by jamesmontemagno** [comment]
Maybe local function issues with F#?

**Comment by RyanBuzzInteractive** [comment]
That would be so ironic ^_^

**Comment by jamesmontemagno** [comment]
I worked with @praeclarum on this and we got it working just fine with ContinueWith. So this is an F# issue or the code is implemented in a way that it is gobbling up the exception.

Here is the new code:

```
namespace FSharpLib

module Library =
    open CSharpLib
    open System.Threading.Tasks

    type FSharpClass () =
        
        member this.TryGetLocation () =
            LocationService.GetLocation().ContinueWith(fun (t:Task<_>) -> printfn "Task %A" t)
```

Here is the output:

```
[0:] Location Permissions needed
Thread started: <Thread Pool> #4
Thread started: <Thread Pool> #5
Thread started: <Thread Pool> #6
Thread started: <Thread Pool> #7
2018-06-21 11:24:06.141 Example.iOS[90527:6425030] Task System.Threading.Tasks.Task`1[Xamarin.Essentials.Location]
[0:] Completed async request
```

**Comment by RyanBuzzInteractive** [comment]
Hi James (+ Frank),

Sorry if I am being stupid, I can't get that to work. I still have exactly the same issue, I can't get the task to return after the permissions request.

I have included an example using the ContinueWith call, and it behaves exactly the same.

It never returns from the permission request, whether you accept (so should get a location) or deny (should get an exception) so it's not just an exception issue. 

I'm happy to ask elsewhere if you think it's definitely a problem with F# itself and not the plugin code. I still feel that there is a way to get around it with the right syntax.

[Example using ContinueWith.zip](https://github.com/xamarin/Essentials/files/2127069/Example.using.ContinueWith.zip)

**Comment by RyanBuzzInteractive** [comment]
Ok, I think I see what you did - you took the f# async out of the equation, you are directly returning the task from your plugin. Of course that would work, as it is literally the same as calling it from C#.

Unfortunately that doesn't help at all, as if you want to use the location in F# you have to await the plugin, which means doing AwaitTask. 

Then up the chain when you want to use your async F# routine, that has to be converted to a Task. 

This is why I set the example up the way I did.

**Comment by RyanBuzzInteractive** [comment]
Another thought - if my example seems a bit out of the ordinary, I believe you can do pure F# Xamarin projects now? In that case, with no C# to await your Task directly, wouldn't you be faced with exactly the same issue?

**Comment by RyanBuzzInteractive** [comment]
Here's a mega simple, pure F# example that literally just calls the plugin directly in ViewDidLoad. It doesn't even show the permissions request here.

If you can get the plugin working properly in this project, then it would solve the other too. Otherwise I think we have to conclude it isn't F# compatible at the moment, for whatever reason.

[Pure F# Example.zip](https://github.com/xamarin/Essentials/files/2127308/Pure.F.Example.zip)

**Comment by RyanBuzzInteractive** [comment]
Here's a mega simple, pure F# example that literally just calls the plugin directly in ViewDidAppear. It never returns after the permissions request.

If you can get the plugin working properly in this project, then it would solve the other too. Otherwise I think we have to conclude it isn't F# compatible at the moment, for whatever reason.

[PureFSharpExample.zip](https://github.com/xamarin/Essentials/files/2127394/PureFSharpExample.zip)

**Comment by RyanBuzzInteractive** [comment]
A quick note - my build is now failing in VS Mac as that doesn't support StartAsTaskImmediate yet. This isn't a bug with the plugin of course but does mean it can't be used on a Mac with F# until that arrives.

**Comment by dsyme** [comment]
> A quick note - my build is now failing in VS Mac as that doesn't support StartAsTaskImmediate yet. This isn't a bug with the plugin of course but does mean it can't be used on a Mac with F# until that arrives.

You can upgrade your project to use FSHarp.Core 4.5.0.  There wsa some bug with VS for Mac that was automatically downgrading 4.3.4 but that has been fixed, you may need to manually edit your project file until then

cc @nosami

**Comment by RyanBuzzInteractive** [comment]
great, thanks :)

**Comment by RyanBuzzInteractive** [comment]
That fixed it on my Mac but it still fails on VSTS, I can see that it is being downgraded even though I have explicitly added 4.5.0 from nuget in every project and even added a binding redirect. I'm sure it will go away once the VSTS machine is updated.

**Comment by RyanBuzzInteractive** [comment]
Hi again @jamesmontemagno  , I just had a thought. I noticed you guys added a MainThreadDispatch plugin to Essentials recently and said that you use it internally already.

Since my problem was that I was unknowingly requesting Location on a background thread, would it be possible for you to force the plugin to run the permissions request on the UI thread and then return the result on the original calling thread? Then fools like me can't make mistakes hehe.

Cheers!

**Comment by jamesmontemagno** [comment]
This API is available: https://docs.microsoft.com/en-us/xamarin/essentials/main-thread

**Comment by RyanBuzzInteractive** [comment]
Heya, yeah I have seen it thanks, that's what I was referring to in my previous message. I was just suggesting that the location plugin marshals any calls to it onto the main thread automatically, wherever they come from (or throw an exception like Don suggested, so it is clear what is going on, rather than just go silent). That way people couldn't make the same mistake I did.

Is there anything in the documentation that says that the plugin must be used from the UI thread? I mean I guess it is common sense but could be good to spell it out?

**Comment by jamesmontemagno** [comment]
ah, i see what you are saying about the permission prompt as that would come from the UI thread itself. 
i mean what we should do is basically detect if we need to prompt for permissions and if you are on a background thread then not allow it. can you file a new issue with more details on the issue you are seeing

**Comment by RyanBuzzInteractive** [comment]
sure ok :)

**Comment by RyanBuzzInteractive** [comment]
I know this is long closed but just thought I would add that the F# VSTS issue I mentioned has been fixed now :) https://developercommunity.visualstudio.com/content/problem/393932/mac-os-builds-are-broken-when-using-modern-f.html

**Comment by vinceg433** [comment]
Oddly enough the F# VSTS issue seems to be back, except now it's forcing v4.5.2 (we are using anonymous records so we need at least 4.6).  I've raised two separate issues with Microsoft over this, they keep closing it saying it is fixed but it's not.  Here's the link to one of them:  https://developercommunity.visualstudio.com/content/problem/712960/f-46-language-features-dont-work-on-vs-for-mac-sta.html

Can I get some clarification on the local agent workaround that's mentioned here?  This has stalled us for over a month so far.
